### PR TITLE
Styling fixes and standardization

### LINKED ISSUE #64: Styling fixes and standardization
- [x] Check and standardize across views and components as needed:
  - [x] Page margins
  - [x] Text color
  - [x] Form input height, background color, font size
  - [x] Button radius
- [x] Fix home page styling
  - [x] Space next to logout
  - [x] New list input location
  - [x] Side margins

Current deployment:
image

### PR DESCRIPTION
**Pull request by andiedoescode**
## Description

Fixed styling and implemented consistent styling.

## Related Issue

Closes #64 

## Acceptance Criteria

- [x] Check and standardize across views and components as needed:
  - [x] Page margins
  - [x] Text color
  - [x] Form input height, background color, font size
  - [x] Button radius
- [x] Fix home page styling
  - [x] Space next to logout
  - [x] New list input location
  - [x] Side margins

## Type of Changes

`style` and `fix`

### Before
Home view
image

List view
image

### After

Home view
image

List view
image

## Testing Steps / QA Criteria

- Open deployment link or pull branch `ap-styling-fix-and-standardization`
- Ensure that Home and List views match screenshots for styling.

### CODE REVIEW

**Review by DevinaG007 — APPROVED** [review]
Love it!! It looks so fresh, so clean ❤️ Thanks Andrea

**Review by sdmisra — APPROVED** [review]
Praise: Thank you immensely for making these changes so last minute, you really addressed some huge issues that we were about to run into in the morning, especially with some of that text defaulting to white on our light background!

**Review by cafloyd — APPROVED** [review]
Nice job, @andiedoescode ! This kind of attention to detail makes such a huge difference, thanks for taking the initiative!

**Review by etiry — APPROVED** [review]
Thank you for doing this!!

**Pull request merged**
